[build]
builder = "nixpacks"

[deploy]
startCommand = "php -S localhost:8000"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
PORT = "8000"

[[services]]
name = "medofolio-db"
source = "medofolio-database"
